version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing dependencies or setup steps, if needed"
  pre_build:
    commands:
      - echo "Pre-build steps, if any"
  build:
    commands:
      - mvn clean package
artifacts:
  files: target/*.jar
